# Generated by Django 4.1 on 2024-03-01 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutygroup',
            name='name',
        ),
    ]
