# Generated by Django 4.1 on 2024-03-01 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0002_remove_dutygroup_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dutygroup',
            old_name='sequence',
            new_name='num',
        ),
    ]
