# Generated by Django 4.1 on 2024-03-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
    ]
