# Generated by Django 4.1 on 2024-03-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='event',
        ),
    ]
