# Generated by Django 4.1 on 2024-03-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_remove_todoitem_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to='user_panel.event'),
        ),
    ]
