# Generated by Django 4.1 on 2024-03-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0004_todoitem_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
