# Generated by Django 4.1 on 2024-03-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_todoitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='order',
        ),
    ]
