# Generated by Django 4.1 on 2024-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0008_alter_todoitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
