# Generated by Django 4.2.9 on 2024-03-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0009_todoitem_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
