# Generated by Django 4.2.9 on 2024-02-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the publication', max_length=200)),
                ('year', models.IntegerField(default=2024)),
                ('author', models.CharField(help_text='eg: J. Zhang, J. Peng, Y. Zhu, D. Hu* and Z. Lan*', max_length=200)),
                ('publisher', models.CharField(max_length=100)),
                ('book_title', models.CharField(max_length=200, verbose_name='Subtitle')),
                ('editor', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_in_Cn', models.CharField(help_text='Enter the title of the funding in Chinese', max_length=200)),
                ('source_in_En', models.CharField(default='National Natural Science Foundation of China', help_text='Enter the funding source in English, eg: National Natural Science Foundation of China', max_length=100)),
                ('source_in_Cn', models.CharField(default='国家自然科学基金委', help_text='Enter the funding source in Chinese,eg: 国家自然科学基金委', max_length=100)),
                ('category_in_En', models.CharField(help_text='Enter the funding category in English, eg: major project', max_length=20)),
                ('category_in_Cn', models.CharField(help_text='Enter the funding category in Chinese,eg: 重点项目', max_length=20)),
                ('start_year', models.IntegerField(default=2024, help_text='Enter the start year')),
                ('start_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Enter the start month')),
                ('end_year', models.IntegerField(default=2024, help_text='Enter the end year')),
                ('end_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Enter the end month')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the publication', max_length=200)),
                ('year', models.IntegerField(default=2024)),
                ('author', models.CharField(help_text='eg: J. Zhang, J. Peng, Y. Zhu, D. Hu* and Z. Lan*', max_length=200)),
                ('journal_name', models.CharField(help_text='Please follow the standard journal abbreviation (ISO4), eg: J. Phys. Chem. Lett.', max_length=100)),
                ('volume', models.CharField(max_length=20)),
                ('page', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the talk', max_length=200)),
                ('conference', models.CharField(help_text='Enter the title of the conference', max_length=200)),
                ('start_date', models.DateField(help_text='Select the start date of the conference')),
                ('end_date', models.DateField(help_text='Select the end date of the conference')),
                ('country_in_CN', models.CharField(help_text='Enter the country of the conference in Chinese', max_length=100)),
                ('city_in_CN', models.CharField(help_text='Enter the city of the conference in Chinese', max_length=100)),
                ('country_in_EN', models.CharField(help_text='Enter the country of the conference in English', max_length=100)),
                ('city_in_EN', models.CharField(help_text='Enter the city of the conference in English', max_length=100)),
                ('category_in_Cn', models.CharField(help_text='Enter the category of the talk, eg: 大会报告', max_length=100)),
            ],
        ),
    ]
