# Generated by Django 4.2.9 on 2024-02-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='eg: J. Zhang, J. Peng, Y. Zhu, D. Hu* and Z. Lan*', max_length=200, verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(max_length=200, verbose_name='Book Title'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='author',
            field=models.CharField(help_text='eg: J. Zhang, J. Peng, Y. Zhu, D. Hu* and Z. Lan*', max_length=200, verbose_name='Authors'),
        ),
    ]
