# Generated by Django 4.2.9 on 2024-02-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='conference',
        ),
        migrations.AddField(
            model_name='talk',
            name='conference_in_CN',
            field=models.CharField(default=1, help_text='Enter the title of the conference in chinese', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='conference_in_EN',
            field=models.CharField(default=1, help_text='Enter the title of the conference in english', max_length=200),
            preserve_default=False,
        ),
    ]
