# Generated by Django 4.2.9 on 2024-02-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_cv', '0002_remove_talk_conference_talk_conference_in_cn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='total_funding',
            field=models.IntegerField(default=100, help_text='Enter the total funding amount (in RMB)', verbose_name='Total Funding'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funding',
            name='source_in_En',
            field=models.CharField(default='NSFC', help_text='Enter the funding source in English, eg: NSFC', max_length=100),
        ),
    ]
