# Generated by Django 4.2.9 on 2024-02-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_cv', '0003_funding_total_funding_alter_funding_source_in_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='direct_funding',
            field=models.IntegerField(default=100, help_text='Enter the direct funding amount (in RMB)', verbose_name='Direct Funding'),
            preserve_default=False,
        ),
    ]
