# Generated by Django 4.2.9 on 2024-02-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_cv', '0004_funding_direct_funding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='direct_funding',
            field=models.IntegerField(help_text='Enter the direct funding amount (in RMB)', verbose_name='Direct Funding (W)'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='total_funding',
            field=models.IntegerField(help_text='Enter the total funding amount (in RMB)', verbose_name='Total Funding (W)'),
        ),
    ]
