# Generated by Django 4.2.9 on 2024-02-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_cv', '0005_alter_funding_direct_funding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='indexed',
            field=models.CharField(default='SCI', max_length=20),
        ),
    ]
